-- СГЕНЕРИРОВАНО tests/gen-catalog.cjs — не редактировать вручную.
-- Каталог заданий CyberPath: стоимость каждого задания в XP для рейтинга.
-- Выполнить в Supabase → SQL Editor после schema.sql (и после каждого изменения курсов).
insert into public.task_catalog (task_id, course_id, points) values
  ('cia_read', 'fundamentals', 5),
  ('cia_ddos', 'fundamentals', 10),
  ('cia_leak', 'fundamentals', 10),
  ('cia_abbr', 'fundamentals', 10),
  ('cia_integrity', 'fundamentals', 10),
  ('cia_risk', 'fundamentals', 10),
  ('cia_stride', 'fundamentals', 15),
  ('cia_nonrep', 'fundamentals', 15),
  ('cia_choice', 'fundamentals', 15),
  ('cia_defense', 'fundamentals', 15),
  ('pw_read', 'fundamentals', 5),
  ('pw_2fa', 'fundamentals', 10),
  ('pw_attack', 'fundamentals', 15),
  ('pw_spray', 'fundamentals', 15),
  ('pw_entropy', 'fundamentals', 10),
  ('pw_best', 'fundamentals', 10),
  ('pw_factor', 'fundamentals', 15),
  ('pw_storage', 'fundamentals', 15),
  ('pw_lab', 'fundamentals', 20),
  ('ph_read', 'fundamentals', 5),
  ('ph_domain', 'fundamentals', 15),
  ('ph_realdomain', 'fundamentals', 20),
  ('ph_term', 'fundamentals', 10),
  ('ph_vishing', 'fundamentals', 15),
  ('ph_spear', 'fundamentals', 15),
  ('ph_lever', 'fundamentals', 15),
  ('ph_action', 'fundamentals', 15),
  ('ph_lab', 'fundamentals', 25),
  ('cmd_read', 'windows', 5),
  ('cmd_dir', 'windows', 10),
  ('cmd_type', 'windows', 10),
  ('cmd_clear', 'windows', 10),
  ('cmd_findstr', 'windows', 15),
  ('cmd_redirect', 'windows', 10),
  ('cmd_choice', 'windows', 15),
  ('cmd_flag', 'windows', 25),
  ('ps_read', 'windows', 5),
  ('ps_verb', 'windows', 10),
  ('ps_read_file', 'windows', 15),
  ('ps_proc', 'windows', 15),
  ('ps_pipe', 'windows', 10),
  ('ps_verb_new', 'windows', 10),
  ('ps_enc', 'windows', 15),
  ('ps_log', 'windows', 15),
  ('wu_read', 'windows', 5),
  ('wu_netuser', 'windows', 15),
  ('wu_uac', 'windows', 15),
  ('wu_icacls', 'windows', 15),
  ('wu_system', 'windows', 15),
  ('wu_priv', 'windows', 15),
  ('wu_choice', 'windows', 15),
  ('wr_read', 'windows', 5),
  ('wr_systeminfo', 'windows', 10),
  ('wr_tasklist', 'windows', 10),
  ('wr_netstat', 'windows', 15),
  ('wr_priv', 'windows', 15),
  ('wr_schtasks', 'windows', 15),
  ('wr_lab', 'windows', 25),
  ('wr_tri', 'windows', 15),
  ('wr_autorun', 'windows', 15),
  ('wr_enc', 'windows', 15),
  ('wr_triage_lab', 'windows', 30),
  ('tcp_read', 'networking', 5),
  ('tcp_https', 'networking', 10),
  ('tcp_ssh', 'networking', 10),
  ('tcp_handshake', 'networking', 15),
  ('tcp_udp', 'networking', 10),
  ('tcp_layer', 'networking', 15),
  ('tcp_telnet', 'networking', 15),
  ('tcp_match', 'networking', 20),
  ('nm_read', 'networking', 5),
  ('nm_version', 'networking', 15),
  ('nm_allports', 'networking', 15),
  ('nm_syn', 'networking', 15),
  ('nm_filtered', 'networking', 15),
  ('nm_os', 'networking', 10),
  ('nm_flag', 'networking', 25),
  ('nm_lab', 'networking', 25),
  ('na_read', 'networking', 5),
  ('na_sniffer', 'networking', 15),
  ('na_mitm', 'networking', 15),
  ('na_arp', 'networking', 15),
  ('na_dns', 'networking', 15),
  ('na_https', 'networking', 15),
  ('na_segment', 'networking', 15),
  ('ow_read', 'web', 5),
  ('ow_idor', 'web', 15),
  ('ow_org', 'web', 10),
  ('ow_first', 'web', 15),
  ('ow_ssrf', 'web', 15),
  ('ow_cve', 'web', 15),
  ('ow_choice', 'web', 15),
  ('sql_read', 'web', 5),
  ('sql_payload', 'web', 15),
  ('sql_defense', 'web', 20),
  ('sql_union', 'web', 15),
  ('sql_blind', 'web', 15),
  ('sql_priv', 'web', 15),
  ('sql_lab', 'web', 25),
  ('xss_read', 'web', 5),
  ('xss_stored', 'web', 15),
  ('xss_reflected', 'web', 15),
  ('xss_csp', 'web', 15),
  ('xss_cookie', 'web', 15),
  ('xss_defense', 'web', 15),
  ('xss_lab', 'web', 25),
  ('wa_read', 'web', 5),
  ('wa_idor', 'web', 15),
  ('wa_csrf', 'web', 15),
  ('wa_token', 'web', 15),
  ('wa_samesite', 'web', 15),
  ('wa_secure', 'web', 10),
  ('wa_obscurity', 'web', 15),
  ('eth_read', 'pentest', 5),
  ('eth_scope', 'pentest', 10),
  ('eth_roe', 'pentest', 10),
  ('eth_blackbox', 'pentest', 15),
  ('eth_bounty', 'pentest', 15),
  ('eth_disclosure', 'pentest', 15),
  ('eth_lab', 'pentest', 25),
  ('meth_read', 'pentest', 5),
  ('meth_first', 'pentest', 15),
  ('meth_last', 'pentest', 15),
  ('meth_privesc', 'pentest', 15),
  ('meth_lateral', 'pentest', 15),
  ('meth_attack', 'pentest', 15),
  ('meth_order', 'pentest', 20),
  ('rp_read', 'pentest', 5),
  ('rp_passive', 'pentest', 15),
  ('rp_dork', 'pentest', 15),
  ('rp_whois', 'pentest', 10),
  ('rp_dns', 'pentest', 15),
  ('rp_active', 'pentest', 15),
  ('pte_read', 'pentest', 5),
  ('pte_msf', 'pentest', 15),
  ('pte_burp', 'pentest', 15),
  ('pte_cvss', 'pentest', 15),
  ('pte_cve', 'pentest', 15),
  ('pte_exec', 'pentest', 15),
  ('enc_read', 'crypto', 5),
  ('enc_b64', 'crypto', 25),
  ('enc_reversible', 'crypto', 10),
  ('enc_hex', 'crypto', 10),
  ('enc_sign', 'crypto', 10),
  ('enc_choice', 'crypto', 15),
  ('enc_lab', 'crypto', 25),
  ('hash_read', 'crypto', 5),
  ('hash_salt', 'crypto', 15),
  ('hash_pw', 'crypto', 15),
  ('hash_len256', 'crypto', 10),
  ('hash_collision', 'crypto', 15),
  ('hash_hmac', 'crypto', 15),
  ('hash_broken', 'crypto', 15),
  ('asym_read', 'crypto', 5),
  ('asym_aes', 'crypto', 10),
  ('asym_pub', 'crypto', 15),
  ('asym_priv', 'crypto', 15),
  ('asym_rsa', 'crypto', 10),
  ('asym_hybrid', 'crypto', 15),
  ('ct_read', 'crypto', 5),
  ('ct_sign', 'crypto', 15),
  ('ct_verify', 'crypto', 15),
  ('ct_ca', 'crypto', 15),
  ('ct_pki', 'crypto', 15),
  ('ct_tls', 'crypto', 10),
  ('ct_warn', 'crypto', 15),
  ('os_read', 'osint', 5),
  ('os_abbr', 'osint', 10),
  ('os_exif', 'osint', 15),
  ('os_archive', 'osint', 15),
  ('os_hibp', 'osint', 15),
  ('os_ethics', 'osint', 15),
  ('osi_lab', 'osint', 25),
  ('so_read', 'osint', 5),
  ('so_site', 'osint', 10),
  ('so_filetype', 'osint', 10),
  ('so_intitle', 'osint', 15),
  ('so_shodan', 'osint', 15),
  ('so_hibp', 'osint', 15),
  ('op_read', 'osint', 5),
  ('op_username', 'osint', 15),
  ('op_reverse', 'osint', 15),
  ('op_chrono', 'osint', 15),
  ('op_puppet', 'osint', 15),
  ('op_privacy', 'osint', 15),
  ('op_line', 'osint', 20),
  ('op_careful', 'osint', 15),
  ('op_line_lab', 'osint', 30),
  ('ad_read', 'ad', 5),
  ('ad_dc', 'ad', 15),
  ('ad_kerb', 'ad', 15),
  ('ad_ldap', 'ad', 15),
  ('ad_tgt', 'ad', 15),
  ('ad_forest', 'ad', 10),
  ('ad_gpo', 'ad', 15),
  ('adr_read', 'ad', 5),
  ('adr_users', 'ad', 15),
  ('adr_kerb', 'ad', 20),
  ('adr_bh', 'ad', 15),
  ('adr_spn', 'ad', 15),
  ('adr_flag', 'ad', 25),
  ('adr_lab', 'ad', 25),
  ('adr_path', 'ad', 20),
  ('adr_ntds', 'ad', 15),
  ('adr_bh_lab', 'ad', 30),
  ('add_read', 'ad', 5),
  ('add_laps', 'ad', 20),
  ('add_pth', 'ad', 20),
  ('add_admins', 'ad', 15),
  ('add_tier', 'ad', 15),
  ('add_event', 'ad', 15),
  ('add_cg', 'ad', 15),
  ('re_read', 'reverse', 5),
  ('re_pe', 'reverse', 15),
  ('re_static', 'reverse', 15),
  ('re_tool', 'reverse', 15),
  ('re_iat', 'reverse', 15),
  ('re_mz', 'reverse', 15),
  ('re_dynamic', 'reverse', 15),
  ('res_read', 'reverse', 5),
  ('res_tool', 'reverse', 15),
  ('res_ioc', 'reverse', 15),
  ('res_b64', 'reverse', 25),
  ('res_rot', 'reverse', 25),
  ('res_lab', 'reverse', 25),
  ('res_pe_lab', 'reverse', 30),
  ('rea_read', 'reverse', 5),
  ('rea_pack', 'reverse', 20),
  ('rea_dbg', 'reverse', 20),
  ('rea_upx', 'reverse', 15),
  ('rea_entropy', 'reverse', 15),
  ('rea_antivm', 'reverse', 15),
  ('rea_oep', 'reverse', 20),
  ('rea_rwx', 'reverse', 15),
  ('rea_dyn_lab', 'reverse', 30),
  ('fo_read', 'forensics', 5),
  ('fo_integrity', 'forensics', 15),
  ('fo_coc', 'forensics', 20),
  ('fo_vol', 'forensics', 15),
  ('fo_wb', 'forensics', 15),
  ('fo_image', 'forensics', 15),
  ('fo_poweroff', 'forensics', 15),
  ('foa_read', 'forensics', 5),
  ('foa_evtx', 'forensics', 15),
  ('foa_mft', 'forensics', 15),
  ('foa_prefetch', 'forensics', 15),
  ('foa_1102', 'forensics', 15),
  ('foa_flag', 'forensics', 25),
  ('foa_lab', 'forensics', 25),
  ('fom_read', 'forensics', 5),
  ('fom_vol', 'forensics', 20),
  ('fom_fileless', 'forensics', 20),
  ('fom_pslist', 'forensics', 15),
  ('fom_malfind', 'forensics', 15),
  ('fom_why', 'forensics', 15),
  ('pha_read', 'phishing', 5),
  ('pha_spear', 'phishing', 15),
  ('pha_whaling', 'phishing', 15),
  ('pha_bec', 'phishing', 15),
  ('pha_attach', 'phishing', 15),
  ('pha_zip', 'phishing', 15),
  ('pha_choice', 'phishing', 15),
  ('pau_read', 'phishing', 5),
  ('pau_spf', 'phishing', 15),
  ('pau_dkim', 'phishing', 15),
  ('pau_dmarc', 'phishing', 15),
  ('pau_reject', 'phishing', 15),
  ('pau_align', 'phishing', 15),
  ('pau_match', 'phishing', 20),
  ('phh_read', 'phishing', 5),
  ('phh_ar', 'phishing', 20),
  ('phh_mismatch', 'phishing', 15),
  ('phh_received', 'phishing', 15),
  ('phh_replyto', 'phishing', 15),
  ('phh_lab', 'phishing', 25),
  ('hdp_read', 'hardening', 5),
  ('hdp_cis', 'hardening', 15),
  ('hdp_priv', 'hardening', 15),
  ('hdp_level', 'hardening', 10),
  ('hdp_asr', 'hardening', 15),
  ('hdp_defaults', 'hardening', 15),
  ('hdw_read', 'hardening', 5),
  ('hdw_smb', 'hardening', 15),
  ('hdw_bitlocker', 'hardening', 15),
  ('hdw_applock', 'hardening', 15),
  ('hdw_whitelist', 'hardening', 15),
  ('hdw_audit', 'hardening', 15),
  ('hdw_lab', 'hardening', 25),
  ('hdb_read', 'hardening', 5),
  ('hdb_patch', 'hardening', 15),
  ('hdb_drift', 'hardening', 15),
  ('hdb_baseline', 'hardening', 15),
  ('hdb_why', 'hardening', 15),
  ('hda_read', 'hardening', 5),
  ('hda_logon', 'hardening', 15),
  ('hda_proc', 'hardening', 20),
  ('hda_sbl', 'hardening', 15),
  ('hda_clear', 'hardening', 15),
  ('hda_lab', 'hardening', 30),
  ('hdn_read', 'hardening', 5),
  ('hdn_mgmt', 'hardening', 20),
  ('hdn_snmp', 'hardening', 20),
  ('hdn_dns', 'hardening', 15),
  ('hdn_cloud', 'hardening', 20),
  ('hdn_net_lab', 'hardening', 30),
  ('hdc_read', 'hardening', 5),
  ('hdc_pwlen', 'hardening', 15),
  ('hdc_smbv1', 'hardening', 20),
  ('hdc_lab', 'hardening', 30),
  ('bts_read', 'blueteam', 5),
  ('bts_siem', 'blueteam', 15),
  ('bts_edr', 'blueteam', 15),
  ('bts_ioc', 'blueteam', 15),
  ('bts_l1', 'blueteam', 10),
  ('bts_hunt', 'blueteam', 15),
  ('bts_ioa', 'blueteam', 15),
  ('bts_lab', 'blueteam', 25),
  ('bts_hyp', 'blueteam', 20),
  ('bts_ttp_hunt', 'blueteam', 15),
  ('bts_hunt_lab', 'blueteam', 30),
  ('bti_read', 'blueteam', 5),
  ('bti_std', 'blueteam', 15),
  ('bti_contain', 'blueteam', 15),
  ('bti_order', 'blueteam', 20),
  ('bti_first', 'blueteam', 10),
  ('bti_recover', 'blueteam', 15),
  ('bti_krbtgt', 'blueteam', 20),
  ('bti_ir_lab', 'blueteam', 30),
  ('bta_read', 'blueteam', 5),
  ('bta_tactics', 'blueteam', 15),
  ('bta_ttp', 'blueteam', 15),
  ('bta_author', 'blueteam', 15),
  ('bta_tactic', 'blueteam', 15),
  ('bta_easiest', 'blueteam', 15),
  ('mwt_read', 'malware', 5),
  ('mwt_static', 'malware', 15),
  ('mwt_dynamic', 'malware', 15),
  ('mwt_worm', 'malware', 15),
  ('mwt_rat', 'malware', 15),
  ('mwt_choice', 'malware', 15),
  ('mwl_read', 'malware', 5),
  ('mwl_snapshot', 'malware', 15),
  ('mwl_vt', 'malware', 15),
  ('mwl_hash', 'malware', 10),
  ('mwl_inetsim', 'malware', 15),
  ('mwl_vtwarn', 'malware', 15),
  ('mwb_read', 'malware', 5),
  ('mwb_persist', 'malware', 15),
  ('mwb_c2', 'malware', 15),
  ('mwb_beacon', 'malware', 15),
  ('mwb_inject', 'malware', 15),
  ('mwb_beaconint', 'malware', 15),
  ('mwb_persist_win', 'malware', 15),
  ('mwb_net_lab', 'malware', 30),
  ('mwb_flag', 'malware', 25),
  ('mwb_lab', 'malware', 25)
on conflict (task_id) do update set course_id = excluded.course_id, points = excluded.points;

-- Разовые бонусы: экзамены, боссы, миссии, инструменты Blue Team, флаги, ежедневный и недельный.
insert into public.bonus_catalog (key, xp, course_id) values
  ('exam:fundamentals', 30, 'fundamentals'),
  ('boss:fundamentals', 50, 'fundamentals'),
  ('exam:windows', 30, 'windows'),
  ('boss:windows', 50, 'windows'),
  ('exam:networking', 30, 'networking'),
  ('boss:networking', 50, 'networking'),
  ('exam:web', 30, 'web'),
  ('boss:web', 50, 'web'),
  ('exam:pentest', 30, 'pentest'),
  ('boss:pentest', 50, 'pentest'),
  ('exam:crypto', 30, 'crypto'),
  ('boss:crypto', 50, 'crypto'),
  ('exam:osint', 30, 'osint'),
  ('boss:osint', 50, 'osint'),
  ('exam:ad', 30, 'ad'),
  ('boss:ad', 50, 'ad'),
  ('exam:reverse', 30, 'reverse'),
  ('boss:reverse', 50, 'reverse'),
  ('exam:forensics', 30, 'forensics'),
  ('boss:forensics', 50, 'forensics'),
  ('exam:phishing', 30, 'phishing'),
  ('boss:phishing', 50, 'phishing'),
  ('exam:hardening', 30, 'hardening'),
  ('boss:hardening', 50, 'hardening'),
  ('exam:blueteam', 30, 'blueteam'),
  ('boss:blueteam', 50, 'blueteam'),
  ('exam:malware', 30, 'malware'),
  ('boss:malware', 50, 'malware'),
  ('mission:m_persistence', 40, null),
  ('mission:m_osint', 30, null),
  ('mission:m_config', 30, null),
  ('tool:hdr_task', 60, null),
  ('tool:ev_task', 70, null),
  ('tool:pk_task', 70, null),
  ('tool:pr_task', 80, null),
  ('tool:fw_task', 70, null),
  ('tool:case_task', 120, null),
  ('flag:headers', 100, null),
  ('flag:events', 100, null),
  ('flag:pcap', 100, null),
  ('flag:procs', 100, null),
  ('flag:firewall', 100, null),
  ('flag:case', 100, null),
  ('daily', 20, null),
  ('weekly', 40, null)
on conflict (key) do update set xp = excluded.xp, course_id = excluded.course_id;

-- Магазин кастомизации (из js/shop.js).
insert into public.shop_items (id, kind, price, req) values
  ('fr_pixel', 'frame', 40, null),
  ('fr_circuit', 'frame', 60, null),
  ('fr_neon', 'frame', 70, null),
  ('fr_glitch', 'frame', 90, null),
  ('fr_vine', 'frame', 120, null),
  ('fr_crystal', 'frame', null, 'exams_5'),
  ('fr_fire', 'frame', null, 'streak_30'),
  ('fr_legend', 'frame', null, 'courses_all'),
  ('nk_sunset', 'nick', 50, null),
  ('nk_ocean', 'nick', 50, null),
  ('nk_terminal', 'nick', 70, null),
  ('nk_rainbow', 'nick', 110, null),
  ('nk_glitch', 'nick', 130, null),
  ('nk_gold', 'nick', 150, null),
  ('nk_ice', 'nick', null, 'tasks_100'),
  ('tt_whitehat', 'title', 30, null),
  ('tt_night', 'title', 30, null),
  ('tt_blue', 'title', 40, null),
  ('tt_red', 'title', 40, null),
  ('tt_packet', 'title', 60, null),
  ('tt_root', 'title', 80, null),
  ('tt_starter', 'title', null, 'first_course'),
  ('tt_hunter', 'title', null, 'flags_all'),
  ('tt_slayer', 'title', null, 'bosses_5'),
  ('tt_steady', 'title', null, 'streak_7'),
  ('bg_circuits', 'bg', 100, null),
  ('bg_terminal', 'bg', 120, null),
  ('bg_starfield', 'bg', 140, null),
  ('bg_radar', 'bg', 160, null),
  ('bg_legend', 'bg', null, 'courses_all'),
  ('fx_sparks', 'effect', 90, null),
  ('fx_snow', 'effect', 90, null),
  ('fx_stars', 'effect', 120, null),
  ('fx_embers', 'effect', 150, null),
  ('fx_matrix', 'effect', 180, null),
  ('fx_flags', 'effect', null, 'flags_all')
on conflict (id) do update set kind = excluded.kind, price = excluded.price, req = excluded.req;
